imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services/all.xml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: session.handler.pdo
    fragments:       ~
    http_method_override: true
    translator: ~

twig:
    debug:            "%kernel.debug%"
    # allow the use of non existing variables
    strict_variables: false

    # override default forms to comply with bootstrap formatting
    form:
        resources:
            - "::bootstrap_forms.html.twig"

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                # let doctrine ignore session table
                schema_filter: ~^(?!session)~
                server_version: 5.6

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
              default:
                  connection: default
                  mappings:
                      default:
                          type: xml
                          prefix: One\CheckJeHuis\Entity
                          alias: Entity
                          dir: "%kernel.root_dir%/../app/config/doctrine"
                          is_bundle: false
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: One\CheckJeHuis\Entity\User
    from_email:
        address: "%fos_user_from_email_address%"
        sender_name: "%fos_user_from_sender_name%"
    resetting:
        retry_ttl: 0 # Value in seconds, logic will use as hours
        token_ttl: 86400

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


trsteel_ckeditor:
    startup_outline_blocks: false
    language: 'nl-be'
    # allow the target="_blank" attributes on links
    html_purifier:
        config: { "Attr.AllowedFrameTargets": [ "_blank" ] }

tactician:
    commandbus:
        default:
            middleware:
                # service ids for all your middlewares, top down. First in, first out.
                - tactician.middleware.validator
                - tactician.middleware.doctrine
                - tactician.middleware.command_handler

knp_snappy:
    pdf:
        enabled:    true
        binary:     ../bin/wkhtmltopdf-amd64
        options:    []

vich_uploader:
    db_driver: orm
    metadata:
        auto_detection: false
        directories:
            - {path: '%kernel.root_dir%/config/vich_uploader', namespace_prefix: 'One\CheckJeHuis'}
    mappings:
        header_logo:
            uri_prefix: /uploads
            upload_destination: '%kernel.root_dir%/../web/uploads'
            namer: vich_uploader.namer_uniqid
        footer_logo:
            uri_prefix: /uploads
            upload_destination: '%kernel.root_dir%/../web/uploads'
            namer: vich_uploader.namer_uniqid
        thermographic_photo_image:
            uri_prefix: /uploads
            upload_destination: '%kernel.root_dir%/../web/uploads'
            namer: vich_uploader.namer_uniqid

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig'     # sliding pagination controls template
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig' # sort link template